"""Draft markdown document generation.

The draft contains everything deterministically extractable (source, creator,
duration, caption, transcript-derived quotes) and clearly marks the sections
that need human/LLM judgment (What This Is synthesis, cross-references,
star rating, category placement).
"""

from __future__ import annotations

import re
from pathlib import Path

DRAFT_BANNER = (
    "> 🔶 **RAW DRAFT — generated by reelscribe.** Deterministic fields are "
    "filled; sections marked `TODO-enrichment` need the judgment pass "
    "(cross-references, star rating, category placement, context notes)."
)


def clean_title(info: dict, max_len: int = 110) -> str:
    """Platform title → human title.

    Facebook titles are often '<views> · <reactions> | <caption start> #tags…'
    — strip the stats prefix and the hashtag tail.
    """
    title = (info.get("title") or "").strip()
    if "|" in title:
        head = title.split("|")[0]
        if "views" in head or "reactions" in head or "·" in head:
            title = title.split("|", 1)[1].strip()
    if "#" in title:
        title = title.split("#", 1)[0].strip()
    title = re.sub(r"\s+", " ", title).rstrip(" .,-—|")
    if len(title) > max_len:
        title = title[:max_len].rsplit(" ", 1)[0] + "…"
    return title or "Untitled reel"


def _creator_tag(uploader: str) -> str:
    return (uploader or "").lower().replace(" ", "-").replace(".", "").replace(",", "")


def _mmss(seconds: float) -> str:
    s = int(round(seconds))
    return f"{s // 60}:{s % 60:02d}" if s >= 60 else f"{s} seconds"


def _canonical_url(info: dict) -> str:
    url = info.get("webpage_url") or info.get("original_url") or ""
    # Prefer a stable desktop watch URL over mobile/share redirects
    vid = info.get("id")
    if vid and "facebook.com" in url:
        return f"https://www.facebook.com/watch/?v={vid}"
    return url


def _clean_caption(desc: str, limit: int = 2200) -> str:
    desc = (desc or "").strip()
    if len(desc) > limit:
        desc = desc[:limit].rsplit(" ", 1)[0] + " …[truncated]"
    return desc


def _key_quote(segments: list[dict]) -> str:
    """Pick the longest contiguous run of transcript text as a candidate
    key-concept quote (up to ~340 chars)."""
    if not segments:
        return ""
    text = " ".join(s["text"] for s in segments)
    text = re.sub(r"\s+", " ", text).strip()
    if len(text) <= 340:
        return text
    cut = text[:340].rsplit(" ", 1)[0]
    return cut + " …"


def write_draft(path: Path, number: int, info: dict, files: dict,
                segments: list[dict], has_speech: bool) -> None:
    title = clean_title(info)
    uploader = info.get("uploader") or info.get("channel") or "unknown"
    duration = float(info.get("duration") or 0)
    caption = _clean_caption(info.get("description", ""))
    quote = _key_quote(segments)
    platform = (info.get("extractor_key") or "Link").replace("Generic", "Link")

    lines = [
        f"# {title}",
        "",
        DRAFT_BANNER,
        "",
        f"**Source:** [{platform}]({_canonical_url(info)})",
        f"**Creator:** {uploader}",
        f"**Duration:** {_mmss(duration)}",
        f"**Video file:** `{files.get('video', '')}`",
        "",
        "## What This Is",
        "",
        "TODO-enrichment — synthesise 1–3 sentences from the transcript + caption below.",
        "",
    ]

    if has_speech:
        lines += [
            "## Key Concept (from transcript — auto-selected, verify)",
            "",
            f'> *"{quote}"*' if quote else "> (transcript too short to quote)",
            "",
        ]
    else:
        lines += [
            "## Audio Note",
            "",
            "Silent/music-only reel — no speech detected by Whisper. Work from the "
            "caption below + the video/thumbnail. **Tier: Inferred** unless the "
            "caption carries full instructions.",
            "",
        ]

    if caption:
        lines += [
            "## Caption (verbatim from the platform)",
            "",
            "> " + caption.replace("\n", "\n> "),
            "",
        ]

    lines += [
        "## The Exercise (step-by-step)",
        "",
        "TODO-enrichment — extract steps from the transcript/caption; if the demo "
        "is visual-only, say so and point at the video.",
        "",
        "## Cross-Reference",
        "",
        "TODO-enrichment — link related reels in this library.",
        "",
        "## Tags",
        "",
        f"TODO-enrichment  #{_creator_tag(uploader)}",
        "",
    ]
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text("\n".join(lines), encoding="utf-8")
